- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Clean old app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a new app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and unzip the frontend code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy the roboshop configuration file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start the nginx service
  ansible.builtin.systemd_service:
    state: started
    name: nginx