- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add the roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and unzip the catalogue code
  ansible.builtin.unarchive:
    src: http://172.31.14.209:8081/repository/catalogue/catalogue-1.0.0.zip
    dest: /app
    remote_src: yes

- name: Copy the catalogue service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start the catalogue service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: catalogue

- name: Copy the mongoDB repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongo client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load the Schema
  ansible.builtin.shell: mongo --host 172.31.23.169 </app/schema/catalogue.js
